# Generated by Django 2.2.6 on 2019-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191102_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave_usuario',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
