# Generated by Django 2.2.6 on 2019-11-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191106_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nusuario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
